/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddContact: typeof import('./components/AddContact.vue')['default']
    AddPerson: typeof import('./components/AddPerson.vue')['default']
    AdminAssignInquiry: typeof import('./components/AdminAssignInquiry.vue')['default']
    AdminChangeAssignment: typeof import('./components/AdminChangeAssignment.vue')['default']
    AdminManageInquiryUser: typeof import('./components/AdminManageInquiryUser.vue')['default']
    AdminReverseInquiry: typeof import('./components/AdminReverseInquiry.vue')['default']
    AdminSearchInquiry: typeof import('./components/AdminSearchInquiry.vue')['default']
    AllPreviousInquiry: typeof import('./components/AllPreviousInquiry.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AssignInquiry: typeof import('./components/AssignInquiry.vue')['default']
    BranchInfo: typeof import('./components/BranchInfo.vue')['default']
    BranchSearchInquiry: typeof import('./components/BranchSearchInquiry.vue')['default']
    ChangeAssignment: typeof import('./components/ChangeAssignment.vue')['default']
    ContractData: typeof import('./components/ContractData.vue')['default']
    CorrectData: typeof import('./components/CorrectData.vue')['default']
    DashboardLayout: typeof import('./components/layouts/DashboardLayout.vue')['default']
    DeleteData: typeof import('./components/DeleteData.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IndividualBranch: typeof import('./components/IndividualBranch.vue')['default']
    IndividualBranchData: typeof import('./components/IndividualBranchData.vue')['default']
    IndividualBranchServiceCharge: typeof import('./components/IndividualBranchServiceCharge.vue')['default']
    InstitutionInfo: typeof import('./components/InstitutionInfo.vue')['default']
    LinkData: typeof import('./components/LinkData.vue')['default']
    LoginView: typeof import('./components/LoginView.vue')['default']
    ManageInquiry: typeof import('./components/ManageInquiry.vue')['default']
    MatchingError: typeof import('./components/MatchingError.vue')['default']
    MonthlyCharge: typeof import('./components/MonthlyCharge.vue')['default']
    MonthlyServiceCharge: typeof import('./components/MonthlyServiceCharge.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NewInquiry: typeof import('./components/NewInquiry.vue')['default']
    NewReport: typeof import('./components/NewReport.vue')['default']
    PendingReport: typeof import('./components/PendingReport.vue')['default']
    PersonInfo: typeof import('./components/PersonInfo.vue')['default']
    ReverseInquiry: typeof import('./components/ReverseInquiry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInquiry: typeof import('./components/SearchInquiry.vue')['default']
    SignUpView: typeof import('./components/SignUpView.vue')['default']
    SubjectData: typeof import('./components/SubjectData.vue')['default']
    SubjectInfo: typeof import('./components/SubjectInfo.vue')['default']
    SuccessPage: typeof import('./components/SuccessPage.vue')['default']
    SummaryReport: typeof import('./components/SummaryReport.vue')['default']
    UnreportedLoan: typeof import('./components/UnreportedLoan.vue')['default']
    UpdateData: typeof import('./components/UpdateData.vue')['default']
    WelcomeMessage: typeof import('./components/WelcomeMessage.vue')['default']
  }
}
